#!/bin/bash

# ===========================================设置各参数（不需要的可以删掉或者前面加# ）=============================================
# 设置文件下载路径
FLIE_PATH='./'

#设置argo-token
TOK='eyJhIjoiNTRhM2QyMDEwZTk0YmU5MDA3NWctOTAwT0RjMUxXRmtZVGN0TURkaE1qWTJNVGcwTUdFdyJ9'

#设置哪吒
NEZHA_SERVER='xxxxxxxxxx'
NEZHA_KEY='xxxxxxxxx'

#哪吒其他默认参数，无需更改
NEZHA_PORT='443'
# 删掉下一行即可关闭tls
NEZHA_TLS='1'
TLS=${NEZHA_TLS:+'--tls'}

#X-RAY配置

# 内置配置了，需要自编译，也可使用下面默认的（想要改变的可以到https://huggingface.co/spaces/sadsadewqeqw/wqeee复制空间编译一个）

# ===========================================设置下载链接（两种平台都要设置，脚本自适应选择下载）=============================================

# 设置x86_64-argo下载地址
 URL_CF='https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64'

# 设置x86_64-NEZHA下载地址
 URL_NEZHA='https://github.com/dsadsadsss/d/releases/download/sd/nezha-amd'

# 设置x86_64-bot下载地址（必须内置配置的版本,没有的可以到https://huggingface.co/spaces/sadsadewqeqw/wqeee复制空间编译一个）
# 下面这个默认配置查看仓库文件xray-config.json
 URL_BOT='https://github.com/dsadsadsss/d/releases/download/sd/kano-6-amd-w'

# 设置arm-argo下载地址
 URL_CF2='https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64'

# 设置arm-NEZHA下载地址
 URL_NEZHA2='https://github.com/dsadsadsss/d/releases/download/sd/nezha-arm'

# 设置arm-bot下载地址（必须内置配置的版本）
# 下面这个默认配置查看仓库文件xray-config.json
 URL_BOT2='https://github.com/dsadsadsss/d/releases/download/sd/kano-6-arm-w'


